name = "backend"
compatibility_date = "2024-08-03"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjllOGI2YTctMjFmMy00ODNkLWE3MmQtODgwNjBlNmM3ZTU5IiwidGVuYW50X2lkIjoiODM5YzEwOTVmN2Y3ZTUxNDMyNDg5MWUwYjdjM2Q0OGJhOTYwNDRkMmU0NjQ1ZGM5YmJjOWMwNzMyMzJmYWRmOSIsImludGVybmFsX3NlY3JldCI6IjA0YzE0ZTQ3LTQ2MWQtNGY3OC1iNmQwLWQwZWI2MjgzYzYwNCJ9.Ol3xd5GBmMCj5bzIooLHcDGJ_48V3FC1NS49wjnroms"
JWT_SECRET = "1234234"